// ==============================
// Types
// ==============================

export type CalendarEventType =
  | "irrigation"
  | "treatment"
  | "fertilization"
  | "harvest"
  | "inspection"
  | "alert"

export type CalendarEventPriority = "low" | "medium" | "high"

export type CalendarEventStatus = "pending" | "in_progress" | "completed"

export interface CalendarEventMeta {
  dose?: string
  product?: string
  waterAmount?: number // litros
  notes?: string
  priority?: CalendarEventPriority
}

export interface CalendarEvent {
  id: string
  title: string
  type: CalendarEventType

  parcelId: string
  parcelName: string

  color: string

  status: CalendarEventStatus

  start: Date
  end: Date

  meta?: CalendarEventMeta
}

// ==============================
// Helpers
// ==============================

const d = (date: string) => new Date(date)

// ==============================
// Mock Data
// ==============================

export const calendarMockData: CalendarEvent[] = [
  {
    id: "event-1",
    title: "Riego parcela norte",
    type: "irrigation",
    parcelId: "parcel-1",
    parcelName: "Olivar La Loma",
    color: "blue",
    status: "completed",
    start: d("2026-05-12T07:00:00"),
    end: d("2026-05-12T09:00:00"),
    meta: {
      waterAmount: 12000,
      notes: "Riego por baja humedad del suelo",
      priority: "high",
    },
  },
  {
    id: "event-2",
    title: "Tratamiento contra prays",
    type: "treatment",
    parcelId: "parcel-1",
    parcelName: "Olivar La Loma",
    color: "red",
    status: "completed",
    start: d("2026-05-14T06:30:00"),
    end: d("2026-05-14T08:00:00"),
    meta: {
      product: "Bacillus thuringiensis",
      dose: "1.5 kg/ha",
      notes: "Aplicar antes de subida de temperatura",
      priority: "high",
    },
  },
  {
    id: "event-3",
    title: "Fertilización de primavera",
    type: "fertilization",
    parcelId: "parcel-2",
    parcelName: "Finca El Cerro",
    color: "green",
    status: "completed",
    start: d("2026-05-17T08:00:00"),
    end: d("2026-05-17T10:00:00"),
    meta: {
      product: "NPK 15-15-15",
      dose: "300 kg/ha",
      priority: "medium",
    },
  },
  {
    id: "event-4",
    title: "Inspección de plagas",
    type: "inspection",
    parcelId: "parcel-2",
    parcelName: "Finca El Cerro",
    color: "yellow",
    status: "completed",
    start: d("2026-05-19T07:30:00"),
    end: d("2026-05-19T08:30:00"),
    meta: {
      notes: "Revisar mosca del olivo",
      priority: "medium",
    },
  },
  {
    id: "event-5",
    title: "Alerta viento fuerte",
    type: "alert",
    parcelId: "parcel-1",
    parcelName: "Olivar La Loma",
    color: "orange",
    status: "pending",
    start: d("2026-05-21T00:00:00"),
    end: d("2026-05-21T23:59:00"),
    meta: {
      notes: "Evitar tratamientos foliares",
      priority: "high",
    },
  },
  {
    id: "event-6",
    title: "Revisión sistema de riego",
    type: "inspection",
    parcelId: "parcel-1",
    parcelName: "Olivar La Loma",
    color: "purple",
    status: "pending",
    start: d("2026-05-24T09:00:00"),
    end: d("2026-05-24T11:00:00"),
    meta: {
      notes: "Comprobar goteros",
      priority: "low",
    },
  },
  {
    id: "event-7",
    title: "Riego correctivo",
    type: "irrigation",
    parcelId: "parcel-2",
    parcelName: "Finca El Cerro",
    color: "blue",
    status: "pending",
    start: d("2026-05-26T06:30:00"),
    end: d("2026-05-26T08:30:00"),
    meta: {
      waterAmount: 9000,
      priority: "high",
    },
  },
  {
    id: "event-8",
    title: "Aplicación cobre",
    type: "treatment",
    parcelId: "parcel-2",
    parcelName: "Finca El Cerro",
    color: "red",
    status: "pending",
    start: d("2026-05-28T07:00:00"),
    end: d("2026-05-28T09:00:00"),
    meta: {
      product: "Oxicloruro de cobre",
      dose: "2 kg/ha",
      priority: "medium",
    },
  },
  {
    id: "event-9",
    title: "Riego sector este",
    type: "irrigation",
    parcelId: "parcel-1",
    parcelName: "Olivar La Loma",
    color: "blue",
    status: "pending",
    start: d("2026-05-28T05:30:00"),
    end: d("2026-05-28T07:00:00"),
    meta: {
      waterAmount: 8000,
      priority: "medium",
    },
  },
  {
    id: "event-10",
    title: "Fertilización foliar",
    type: "fertilization",
    parcelId: "parcel-1",
    parcelName: "Olivar La Loma",
    color: "green",
    status: "pending",
    start: d("2026-05-28T09:30:00"),
    end: d("2026-05-28T10:30:00"),
    meta: {
      product: "Aminoácidos",
      dose: "1.2 L/ha",
      priority: "low",
    },
  },
  {
    id: "event-11",
    title: "Inspección de goteros",
    type: "inspection",
    parcelId: "parcel-2",
    parcelName: "Finca El Cerro",
    color: "yellow",
    status: "pending",
    start: d("2026-05-28T11:00:00"),
    end: d("2026-05-28T12:00:00"),
    meta: {
      notes: "Detectar obstrucciones",
      priority: "low",
    },
  },
  {
    id: "event-12",
    title: "Tratamiento preventivo",
    type: "treatment",
    parcelId: "parcel-1",
    parcelName: "Olivar La Loma",
    color: "red",
    status: "pending",
    start: d("2026-05-28T12:30:00"),
    end: d("2026-05-28T13:30:00"),
    meta: {
      product: "Azufre mojable",
      dose: "3 kg/ha",
      priority: "medium",
    },
  },
  {
    id: "event-13",
    title: "Revisión humedad suelo",
    type: "inspection",
    parcelId: "parcel-1",
    parcelName: "Olivar La Loma",
    color: "yellow",
    status: "pending",
    start: d("2026-05-28T14:00:00"),
    end: d("2026-05-28T14:45:00"),
    meta: {
      notes: "Sensor 3 y 4",
      priority: "medium",
    },
  },
  {
    id: "event-14",
    title: "Riego apoyo parcela sur",
    type: "irrigation",
    parcelId: "parcel-2",
    parcelName: "Finca El Cerro",
    color: "blue",
    status: "pending",
    start: d("2026-05-28T15:00:00"),
    end: d("2026-05-28T16:30:00"),
    meta: {
      waterAmount: 7000,
      priority: "high",
    },
  },
  {
    id: "event-15",
    title: "Aplicación correctiva",
    type: "treatment",
    parcelId: "parcel-2",
    parcelName: "Finca El Cerro",
    color: "red",
    status: "pending",
    start: d("2026-05-28T17:00:00"),
    end: d("2026-05-28T18:00:00"),
    meta: {
      product: "Quelato de hierro",
      dose: "2 L/ha",
      priority: "high",
    },
  },
  {
    id: "event-16",
    title: "Alerta calor extremo",
    type: "alert",
    parcelId: "parcel-1",
    parcelName: "Olivar La Loma",
    color: "orange",
    status: "pending",
    start: d("2026-05-28T00:00:00"),
    end: d("2026-05-28T23:59:00"),
    meta: {
      notes: "Evitar labores en horas centrales",
      priority: "high",
    },
  },
  {
    id: "event-17",
    title: "Fertilización potasio",
    type: "fertilization",
    parcelId: "parcel-2",
    parcelName: "Finca El Cerro",
    color: "green",
    status: "pending",
    start: d("2026-05-28T18:30:00"),
    end: d("2026-05-28T19:30:00"),
    meta: {
      product: "K2O",
      dose: "200 kg/ha",
      priority: "medium",
    },
  },
  {
    id: "event-18",
    title: "Inspección de plagas nocturna",
    type: "inspection",
    parcelId: "parcel-1",
    parcelName: "Olivar La Loma",
    color: "yellow",
    status: "pending",
    start: d("2026-05-28T20:30:00"),
    end: d("2026-05-28T21:30:00"),
    meta: {
      notes: "Trampas de feromonas",
      priority: "low",
    },
  },
  {
    id: "event-19",
    title: "Riego inicial de campaña",
    type: "irrigation",
    parcelId: "parcel-2",
    parcelName: "Finca El Cerro",
    color: "blue",
    status: "completed",
    start: d("2026-05-07T06:00:00"),
    end: d("2026-05-07T08:00:00"),
    meta: {
      waterAmount: 8500,
      priority: "medium",
    },
  },
  {
    id: "event-20",
    title: "Inspección de brotes",
    type: "inspection",
    parcelId: "parcel-1",
    parcelName: "Olivar La Loma",
    color: "yellow",
    status: "completed",
    start: d("2026-05-07T09:00:00"),
    end: d("2026-05-07T10:00:00"),
    meta: {
      notes: "Evaluar vigor vegetativo",
      priority: "low",
    },
  },
  {
    id: "event-21",
    title: "Tratamiento fungicida",
    type: "treatment",
    parcelId: "parcel-2",
    parcelName: "Finca El Cerro",
    color: "red",
    status: "completed",
    start: d("2026-05-07T18:00:00"),
    end: d("2026-05-07T19:30:00"),
    meta: {
      product: "Cobre sistémico",
      dose: "1.8 kg/ha",
      priority: "medium",
    },
  },
  {
    id: "event-22",
    title: "Fertilización nitrogenada",
    type: "fertilization",
    parcelId: "parcel-1",
    parcelName: "Olivar La Loma",
    color: "green",
    status: "completed",
    start: d("2026-05-14T12:00:00"),
    end: d("2026-05-14T13:00:00"),
    meta: {
      product: "Urea",
      dose: "180 kg/ha",
      priority: "medium",
    },
  },
  {
    id: "event-23",
    title: "Inspección de prays",
    type: "inspection",
    parcelId: "parcel-1",
    parcelName: "Olivar La Loma",
    color: "yellow",
    status: "completed",
    start: d("2026-05-14T16:00:00"),
    end: d("2026-05-14T17:00:00"),
    meta: {
      notes: "Revisión de trampas",
      priority: "medium",
    },
  },
  {
    id: "event-24",
    title: "Riego de apoyo",
    type: "irrigation",
    parcelId: "parcel-2",
    parcelName: "Finca El Cerro",
    color: "blue",
    status: "completed",
    start: d("2026-05-14T18:30:00"),
    end: d("2026-05-14T20:00:00"),
    meta: {
      waterAmount: 6500,
      priority: "high",
    },
  },
  {
    id: "event-25",
    title: "Inicio de recolección temprana",
    type: "harvest",
    parcelId: "parcel-1",
    parcelName: "Olivar La Loma",
    color: "purple",
    status: "pending",
    start: d("2026-05-21T07:30:00"),
    end: d("2026-05-21T11:30:00"),
    meta: {
      notes: "Cuadrilla 1",
      priority: "high",
    },
  },
  {
    id: "event-26",
    title: "Tratamiento post-lluvia",
    type: "treatment",
    parcelId: "parcel-2",
    parcelName: "Finca El Cerro",
    color: "red",
    status: "pending",
    start: d("2026-05-21T12:30:00"),
    end: d("2026-05-21T14:00:00"),
    meta: {
      product: "Fosfonato potásico",
      dose: "2 L/ha",
      priority: "high",
    },
  },
  {
    id: "event-27",
    title: "Inspección de maquinaria",
    type: "inspection",
    parcelId: "parcel-2",
    parcelName: "Finca El Cerro",
    color: "yellow",
    status: "pending",
    start: d("2026-05-21T15:30:00"),
    end: d("2026-05-21T16:30:00"),
    meta: {
      notes: "Revisar atomizadores",
      priority: "low",
    },
  },
  {
    id: "event-28",
    title: "Fertilización potasio foliar",
    type: "fertilization",
    parcelId: "parcel-1",
    parcelName: "Olivar La Loma",
    color: "green",
    status: "pending",
    start: d("2026-05-21T17:30:00"),
    end: d("2026-05-21T18:30:00"),
    meta: {
      product: "K foliar",
      dose: "1.5 L/ha",
      priority: "medium",
    },
  },
  {
    id: "event-29",
    title: "Alerta rachas de viento",
    type: "alert",
    parcelId: "parcel-1",
    parcelName: "Olivar La Loma",
    color: "orange",
    status: "completed",
    start: d("2026-05-07T00:00:00"),
    end: d("2026-05-07T23:59:00"),
    meta: {
      notes: "Evitar aplicaciones foliares",
      priority: "high",
    },
  },
  {
    id: "event-30",
    title: "Revisión de trampas",
    type: "inspection",
    parcelId: "parcel-2",
    parcelName: "Finca El Cerro",
    color: "yellow",
    status: "completed",
    start: d("2026-05-07T10:30:00"),
    end: d("2026-05-07T11:30:00"),
    meta: {
      notes: "Conteo de capturas",
      priority: "low",
    },
  },
  {
    id: "event-31",
    title: "Aplicación de boro",
    type: "fertilization",
    parcelId: "parcel-2",
    parcelName: "Finca El Cerro",
    color: "green",
    status: "completed",
    start: d("2026-05-07T12:00:00"),
    end: d("2026-05-07T13:00:00"),
    meta: {
      product: "Boro",
      dose: "0.8 L/ha",
      priority: "medium",
    },
  },
  {
    id: "event-32",
    title: "Control de repilo",
    type: "treatment",
    parcelId: "parcel-1",
    parcelName: "Olivar La Loma",
    color: "red",
    status: "completed",
    start: d("2026-05-07T14:30:00"),
    end: d("2026-05-07T15:30:00"),
    meta: {
      product: "Mancozeb",
      dose: "2.2 kg/ha",
      priority: "high",
    },
  },
  {
    id: "event-33",
    title: "Riego de refuerzo",
    type: "irrigation",
    parcelId: "parcel-1",
    parcelName: "Olivar La Loma",
    color: "blue",
    status: "completed",
    start: d("2026-05-07T16:00:00"),
    end: d("2026-05-07T17:00:00"),
    meta: {
      waterAmount: 5200,
      priority: "medium",
    },
  },
  {
    id: "event-34",
    title: "Chequeo de presión",
    type: "inspection",
    parcelId: "parcel-1",
    parcelName: "Olivar La Loma",
    color: "yellow",
    status: "completed",
    start: d("2026-05-07T19:45:00"),
    end: d("2026-05-07T20:30:00"),
    meta: {
      notes: "Sector 2 y 3",
      priority: "low",
    },
  },
  {
    id: "event-35",
    title: "Muestreo de humedad",
    type: "inspection",
    parcelId: "parcel-2",
    parcelName: "Finca El Cerro",
    color: "yellow",
    status: "completed",
    start: d("2026-05-07T21:00:00"),
    end: d("2026-05-07T22:00:00"),
    meta: {
      notes: "Sondas 1 y 2",
      priority: "medium",
    },
  },
  {
    id: "event-36",
    title: "Alerta humedad alta",
    type: "alert",
    parcelId: "parcel-2",
    parcelName: "Finca El Cerro",
    color: "orange",
    status: "completed",
    start: d("2026-05-14T00:00:00"),
    end: d("2026-05-14T23:59:00"),
    meta: {
      notes: "Vigilar aparición de hongos",
      priority: "high",
    },
  },
  {
    id: "event-37",
    title: "Riego temprano",
    type: "irrigation",
    parcelId: "parcel-1",
    parcelName: "Olivar La Loma",
    color: "blue",
    status: "completed",
    start: d("2026-05-14T05:00:00"),
    end: d("2026-05-14T06:00:00"),
    meta: {
      waterAmount: 4800,
      priority: "medium",
    },
  },
  {
    id: "event-38",
    title: "Revisión de brotes",
    type: "inspection",
    parcelId: "parcel-2",
    parcelName: "Finca El Cerro",
    color: "yellow",
    status: "completed",
    start: d("2026-05-14T09:00:00"),
    end: d("2026-05-14T10:00:00"),
    meta: {
      notes: "Comparar con semana previa",
      priority: "low",
    },
  },
  {
    id: "event-39",
    title: "Fertilización calcio",
    type: "fertilization",
    parcelId: "parcel-2",
    parcelName: "Finca El Cerro",
    color: "green",
    status: "completed",
    start: d("2026-05-14T10:30:00"),
    end: d("2026-05-14T11:30:00"),
    meta: {
      product: "Calcio líquido",
      dose: "2 L/ha",
      priority: "medium",
    },
  },
  {
    id: "event-40",
    title: "Tratamiento de refuerzo",
    type: "treatment",
    parcelId: "parcel-1",
    parcelName: "Olivar La Loma",
    color: "red",
    status: "completed",
    start: d("2026-05-14T14:00:00"),
    end: d("2026-05-14T15:00:00"),
    meta: {
      product: "Aceite mineral",
      dose: "1.5 L/ha",
      priority: "medium",
    },
  },
  {
    id: "event-41",
    title: "Inspección nocturna",
    type: "inspection",
    parcelId: "parcel-1",
    parcelName: "Olivar La Loma",
    color: "yellow",
    status: "completed",
    start: d("2026-05-14T20:30:00"),
    end: d("2026-05-14T21:30:00"),
    meta: {
      notes: "Revisión de focos",
      priority: "low",
    },
  },
  {
    id: "event-42",
    title: "Riego previo a cosecha",
    type: "irrigation",
    parcelId: "parcel-1",
    parcelName: "Olivar La Loma",
    color: "blue",
    status: "pending",
    start: d("2026-05-21T05:30:00"),
    end: d("2026-05-21T07:00:00"),
    meta: {
      waterAmount: 6000,
      priority: "medium",
    },
  },
  {
    id: "event-43",
    title: "Chequeo de cajas",
    type: "inspection",
    parcelId: "parcel-1",
    parcelName: "Olivar La Loma",
    color: "yellow",
    status: "pending",
    start: d("2026-05-21T11:45:00"),
    end: d("2026-05-21T12:15:00"),
    meta: {
      notes: "Inventario de campo",
      priority: "low",
    },
  },
  {
    id: "event-44",
    title: "Riego de mantenimiento",
    type: "irrigation",
    parcelId: "parcel-2",
    parcelName: "Finca El Cerro",
    color: "blue",
    status: "pending",
    start: d("2026-05-21T18:45:00"),
    end: d("2026-05-21T19:45:00"),
    meta: {
      waterAmount: 4200,
      priority: "medium",
    },
  },
  {
    id: "event-45",
    title: "Tratamiento correctivo",
    type: "treatment",
    parcelId: "parcel-2",
    parcelName: "Finca El Cerro",
    color: "red",
    status: "pending",
    start: d("2026-05-21T20:00:00"),
    end: d("2026-05-21T21:00:00"),
    meta: {
      product: "Cobre",
      dose: "1.5 kg/ha",
      priority: "high",
    },
  },
  {
    id: "event-46",
    title: "Inspección final del día",
    type: "inspection",
    parcelId: "parcel-2",
    parcelName: "Finca El Cerro",
    color: "yellow",
    status: "pending",
    start: d("2026-05-21T21:30:00"),
    end: d("2026-05-21T22:00:00"),
    meta: {
      notes: "Registrar incidencias",
      priority: "low",
    },
  },
  {
    id: "event-47",
    title: "Riego de amanecer",
    type: "irrigation",
    parcelId: "parcel-1",
    parcelName: "Olivar La Loma",
    color: "blue",
    status: "completed",
    start: d("2026-04-30T05:30:00"),
    end: d("2026-04-30T07:00:00"),
    meta: {
      waterAmount: 7000,
      priority: "medium",
    },
  },
  {
    id: "event-48",
    title: "Inspección de floración",
    type: "inspection",
    parcelId: "parcel-1",
    parcelName: "Olivar La Loma",
    color: "yellow",
    status: "completed",
    start: d("2026-04-30T08:00:00"),
    end: d("2026-04-30T09:00:00"),
    meta: {
      notes: "Estado de botones florales",
      priority: "medium",
    },
  },
  {
    id: "event-49",
    title: "Fertilización de arranque",
    type: "fertilization",
    parcelId: "parcel-2",
    parcelName: "Finca El Cerro",
    color: "green",
    status: "completed",
    start: d("2026-04-30T09:30:00"),
    end: d("2026-04-30T10:30:00"),
    meta: {
      product: "NPK 20-10-10",
      dose: "250 kg/ha",
      priority: "medium",
    },
  },
  {
    id: "event-50",
    title: "Tratamiento contra repilo",
    type: "treatment",
    parcelId: "parcel-2",
    parcelName: "Finca El Cerro",
    color: "red",
    status: "completed",
    start: d("2026-04-30T11:00:00"),
    end: d("2026-04-30T12:00:00"),
    meta: {
      product: "Cobre oxicloruro",
      dose: "2 kg/ha",
      priority: "high",
    },
  },
  {
    id: "event-51",
    title: "Revisión de válvulas",
    type: "inspection",
    parcelId: "parcel-1",
    parcelName: "Olivar La Loma",
    color: "yellow",
    status: "completed",
    start: d("2026-04-30T12:30:00"),
    end: d("2026-04-30T13:15:00"),
    meta: {
      notes: "Sector norte",
      priority: "low",
    },
  },
  {
    id: "event-52",
    title: "Riego de apoyo",
    type: "irrigation",
    parcelId: "parcel-2",
    parcelName: "Finca El Cerro",
    color: "blue",
    status: "completed",
    start: d("2026-04-30T14:00:00"),
    end: d("2026-04-30T15:30:00"),
    meta: {
      waterAmount: 6200,
      priority: "high",
    },
  },
  {
    id: "event-53",
    title: "Aplicación de micronutrientes",
    type: "fertilization",
    parcelId: "parcel-1",
    parcelName: "Olivar La Loma",
    color: "green",
    status: "completed",
    start: d("2026-04-30T16:00:00"),
    end: d("2026-04-30T17:00:00"),
    meta: {
      product: "Micros",
      dose: "1 L/ha",
      priority: "low",
    },
  },
  {
    id: "event-54",
    title: "Tratamiento preventivo",
    type: "treatment",
    parcelId: "parcel-1",
    parcelName: "Olivar La Loma",
    color: "red",
    status: "completed",
    start: d("2026-04-30T17:30:00"),
    end: d("2026-04-30T18:30:00"),
    meta: {
      product: "Azufre",
      dose: "2.5 kg/ha",
      priority: "medium",
    },
  },
  {
    id: "event-55",
    title: "Alerta lluvia",
    type: "alert",
    parcelId: "parcel-2",
    parcelName: "Finca El Cerro",
    color: "orange",
    status: "completed",
    start: d("2026-04-30T00:00:00"),
    end: d("2026-04-30T23:59:00"),
    meta: {
      notes: "Revisar drenajes",
      priority: "high",
    },
  },
  {
    id: "event-56",
    title: "Inspección de cierre",
    type: "inspection",
    parcelId: "parcel-2",
    parcelName: "Finca El Cerro",
    color: "yellow",
    status: "completed",
    start: d("2026-04-30T20:00:00"),
    end: d("2026-04-30T21:00:00"),
    meta: {
      notes: "Anotar incidencias",
      priority: "low",
    },
  },
]
