export interface DemoEvent {
  title: string
  description: string
  category: string
  color: string
  tags: string[]
  isRead: number
  startTimeOffset: { days: number; hour: number; minute: number }
  endTimeOffset: { days: number; hour: number; minute: number }
  parcelIndex: number
}

export const demoEvents: DemoEvent[] = [
  {
    title: 'Riego programado',
    description: 'Revisar sistema de riego y verificar presión',
    startTimeOffset: { days: 0, hour: 9, minute: 0 },
    endTimeOffset: { days: 0, hour: 10, minute: 0 },
    category: 'Riego',
    color: '#3b82f6',
    tags: ['urgente', 'mantenimiento'],
    isRead: 0,
    parcelIndex: 0,
  },
  {
    title: 'Aplicación de fertilizante',
    description: 'Aplicar fertilizante NPK en parcela norte',
    startTimeOffset: { days: 1, hour: 8, minute: 0 },
    endTimeOffset: { days: 1, hour: 10, minute: 0 },
    category: 'Fertilización',
    color: '#10b981',
    tags: ['fertilizante'],
    isRead: 0,
    parcelIndex: 0,
  },
  {
    title: 'Inspección de plagas',
    description: 'Revisar almendros en busca de señales de plagas',
    startTimeOffset: { days: 7, hour: 11, minute: 0 },
    endTimeOffset: { days: 7, hour: 12, minute: 30 },
    category: 'Sanidad',
    color: '#f59e0b',
    tags: ['inspección'],
    isRead: 0,
    parcelIndex: 1,
  },
  {
    title: 'Poda de invierno',
    description: 'Realizar poda de formación en viñedos',
    startTimeOffset: { days: 3, hour: 7, minute: 0 },
    endTimeOffset: { days: 3, hour: 12, minute: 0 },
    category: 'Mantenimiento',
    color: '#8b5cf6',
    tags: ['poda', 'viñedo'],
    isRead: 0,
    parcelIndex: 2,
  },
  {
    title: 'Cosecha de aceitunas',
    description: 'Iniciar recolección de aceitunas maduras',
    startTimeOffset: { days: 14, hour: 6, minute: 0 },
    endTimeOffset: { days: 14, hour: 18, minute: 0 },
    category: 'Cosecha',
    color: '#ec4899',
    tags: ['cosecha', 'aceitunas'],
    isRead: 0,
    parcelIndex: 0,
  },
  {
    title: 'Análisis de suelo',
    description: 'Tomar muestras para análisis químico del suelo',
    startTimeOffset: { days: 5, hour: 10, minute: 0 },
    endTimeOffset: { days: 5, hour: 11, minute: 30 },
    category: 'Análisis',
    color: '#14b8a6',
    tags: ['análisis', 'suelo'],
    isRead: 0,
    parcelIndex: 1,
  },
  {
    title: 'Mantenimiento de tractores',
    description: 'Revisión general y cambio de aceite de la maquinaria',
    startTimeOffset: { days: 2, hour: 14, minute: 0 },
    endTimeOffset: { days: 2, hour: 16, minute: 30 },
    category: 'Mantenimiento',
    color: '#8b5cf6',
    tags: ['maquinaria', 'mantenimiento'],
    isRead: 0,
    parcelIndex: 0,
  },
  {
    title: 'Tratamiento fitosanitario',
    description: 'Aplicación de fungicida preventivo en cultivo',
    startTimeOffset: { days: 4, hour: 7, minute: 30 },
    endTimeOffset: { days: 4, hour: 9, minute: 0 },
    category: 'Sanidad',
    color: '#f59e0b',
    tags: ['tratamiento', 'fitosanitario'],
    isRead: 1,
    parcelIndex: 2,
  },
  {
    title: 'Revisión de invernaderos',
    description: 'Inspeccionar estructura y sistemas de ventilación',
    startTimeOffset: { days: 6, hour: 10, minute: 0 },
    endTimeOffset: { days: 6, hour: 11, minute: 0 },
    category: 'Mantenimiento',
    color: '#8b5cf6',
    tags: ['invernadero', 'inspección'],
    isRead: 0,
    parcelIndex: 1,
  },
  {
    title: 'Siembra de hortalizas',
    description: 'Plantar tomates y pimientos en invernadero',
    startTimeOffset: { days: 8, hour: 8, minute: 0 },
    endTimeOffset: { days: 8, hour: 13, minute: 0 },
    category: 'Siembra',
    color: '#06b6d4',
    tags: ['siembra', 'hortalizas'],
    isRead: 0,
    parcelIndex: 2,
  },
  {
    title: 'Control de malezas',
    description: 'Eliminación de malas hierbas en parcela central',
    startTimeOffset: { days: 9, hour: 7, minute: 0 },
    endTimeOffset: { days: 9, hour: 10, minute: 0 },
    category: 'Mantenimiento',
    color: '#8b5cf6',
    tags: ['malezas', 'herbicida'],
    isRead: 1,
    parcelIndex: 0,
  },
  {
    title: 'Instalación de riego por goteo',
    description: 'Montar nuevo sistema de riego en parcela este',
    startTimeOffset: { days: 10, hour: 8, minute: 0 },
    endTimeOffset: { days: 10, hour: 17, minute: 0 },
    category: 'Riego',
    color: '#3b82f6',
    tags: ['instalación', 'riego'],
    isRead: 0,
    parcelIndex: 1,
  },
  {
    title: 'Recogida de frutos secos',
    description: 'Cosecha de almendras de la parcela sur',
    startTimeOffset: { days: 12, hour: 6, minute: 30 },
    endTimeOffset: { days: 12, hour: 15, minute: 0 },
    category: 'Cosecha',
    color: '#ec4899',
    tags: ['cosecha', 'almendras'],
    isRead: 0,
    parcelIndex: 1,
  },
  {
    title: 'Aplicación de compost',
    description: 'Distribuir compost orgánico en parcelas',
    startTimeOffset: { days: 11, hour: 9, minute: 0 },
    endTimeOffset: { days: 11, hour: 12, minute: 0 },
    category: 'Fertilización',
    color: '#10b981',
    tags: ['compost', 'orgánico'],
    isRead: 0,
    parcelIndex: 2,
  },
  {
    title: 'Medición de pH del agua',
    description: 'Análisis de calidad del agua de riego',
    startTimeOffset: { days: 13, hour: 11, minute: 0 },
    endTimeOffset: { days: 13, hour: 12, minute: 0 },
    category: 'Análisis',
    color: '#14b8a6',
    tags: ['análisis', 'agua'],
    isRead: 1,
    parcelIndex: 0,
  },
  {
    title: 'Poda de árboles frutales',
    description: 'Poda de mantenimiento en frutales',
    startTimeOffset: { days: 15, hour: 7, minute: 30 },
    endTimeOffset: { days: 15, hour: 11, minute: 30 },
    category: 'Mantenimiento',
    color: '#8b5cf6',
    tags: ['poda', 'frutales'],
    isRead: 0,
    parcelIndex: 2,
  },
  {
    title: 'Revisión meteorológica',
    description: 'Verificar estación meteorológica y sensores',
    startTimeOffset: { days: 16, hour: 10, minute: 0 },
    endTimeOffset: { days: 16, hour: 10, minute: 45 },
    category: 'Mantenimiento',
    color: '#8b5cf6',
    tags: ['meteorología', 'sensores'],
    isRead: 0,
    parcelIndex: 1,
  },
  {
    title: 'Capacitación de personal',
    description: 'Formación en uso de nueva maquinaria agrícola',
    startTimeOffset: { days: 18, hour: 9, minute: 0 },
    endTimeOffset: { days: 18, hour: 13, minute: 0 },
    category: 'Formación',
    color: '#f97316',
    tags: ['formación', 'equipo'],
    isRead: 0,
    parcelIndex: 0,
  },
  {
    title: 'Inspección de colmenas',
    description: 'Revisar estado de las colmenas y producción de miel',
    startTimeOffset: { days: 19, hour: 15, minute: 0 },
    endTimeOffset: { days: 19, hour: 16, minute: 30 },
    category: 'Ganadería',
    color: '#eab308',
    tags: ['apicultura', 'inspección'],
    isRead: 0,
    parcelIndex: 2,
  },
  {
    title: 'Reparación de cercas',
    description: 'Arreglar cercado perimetral dañado',
    startTimeOffset: { days: 20, hour: 8, minute: 0 },
    endTimeOffset: { days: 20, hour: 12, minute: 0 },
    category: 'Mantenimiento',
    color: '#8b5cf6',
    tags: ['reparación', 'infraestructura'],
    isRead: 1,
    parcelIndex: 1,
  },
]
