export interface DemoTransaction {
  type: string
  category: string
  concept: string
  amount: number
  paymentMethod: string
  invoiceNumber?: string
  daysAgo: number
  description: string
  parcelIndex: number
}

export const demoTransactions: DemoTransaction[] = [
  {
    type: 'gasto',
    category: 'Insumos',
    concept: 'Fertilizante NPK',
    amount: 250.5,
    paymentMethod: 'transferencia',
    invoiceNumber: 'INV-2024-001',
    daysAgo: 5,
    description: 'Compra de fertilizante para la temporada',
    parcelIndex: 0,
  },
  {
    type: 'ingreso',
    category: 'Ventas',
    concept: 'Venta de aceitunas',
    amount: 1500.0,
    paymentMethod: 'transferencia',
    daysAgo: 10,
    description: 'Venta de la última cosecha',
    parcelIndex: 0,
  },
  {
    type: 'gasto',
    category: 'Mantenimiento',
    concept: 'Reparación sistema de riego',
    amount: 180.0,
    paymentMethod: 'efectivo',
    daysAgo: 3,
    description: 'Reparación de tubería principal',
    parcelIndex: 1,
  },
  {
    type: 'gasto',
    category: 'Insumos',
    concept: 'Herbicida selectivo',
    amount: 95.75,
    paymentMethod: 'tarjeta',
    invoiceNumber: 'INV-2024-002',
    daysAgo: 7,
    description: 'Compra de herbicida para control de malas hierbas',
    parcelIndex: 2,
  },
  {
    type: 'ingreso',
    category: 'Ventas',
    concept: 'Venta de vino',
    amount: 2300.0,
    paymentMethod: 'transferencia',
    daysAgo: 15,
    description: 'Venta de producción de vino del año anterior',
    parcelIndex: 2,
  },
  {
    type: 'gasto',
    category: 'Servicios',
    concept: 'Análisis de laboratorio',
    amount: 120.0,
    paymentMethod: 'transferencia',
    invoiceNumber: 'INV-2024-003',
    daysAgo: 8,
    description: 'Análisis de suelo y agua',
    parcelIndex: 1,
  },
  {
    type: 'gasto',
    category: 'Maquinaria',
    concept: 'Alquiler de tractor',
    amount: 350.0,
    paymentMethod: 'transferencia',
    daysAgo: 12,
    description: 'Alquiler de tractor para labores de arado',
    parcelIndex: 0,
  },
  {
    type: 'ingreso',
    category: 'Ventas',
    concept: 'Venta de almendras',
    amount: 850.0,
    paymentMethod: 'efectivo',
    daysAgo: 20,
    description: 'Venta de almendras de la temporada',
    parcelIndex: 1,
  },
  {
    type: 'gasto',
    category: 'Insumos',
    concept: 'Semillas de tomate',
    amount: 145.0,
    paymentMethod: 'tarjeta',
    invoiceNumber: 'INV-2024-004',
    daysAgo: 2,
    description: 'Compra de semillas híbridas para invernadero',
    parcelIndex: 2,
  },
  {
    type: 'gasto',
    category: 'Servicios',
    concept: 'Asesoría agronómica',
    amount: 280.0,
    paymentMethod: 'transferencia',
    invoiceNumber: 'INV-2024-005',
    daysAgo: 14,
    description: 'Consultoría para optimización de cultivos',
    parcelIndex: 0,
  },
  {
    type: 'ingreso',
    category: 'Ventas',
    concept: 'Venta de tomates',
    amount: 675.5,
    paymentMethod: 'transferencia',
    daysAgo: 6,
    description: 'Venta de tomates a restaurante local',
    parcelIndex: 2,
  },
  {
    type: 'gasto',
    category: 'Mano de obra',
    concept: 'Jornaleros cosecha',
    amount: 520.0,
    paymentMethod: 'efectivo',
    daysAgo: 18,
    description: 'Pago de jornaleros para cosecha de aceitunas',
    parcelIndex: 0,
  },
  {
    type: 'gasto',
    category: 'Insumos',
    concept: 'Fungicida',
    amount: 165.25,
    paymentMethod: 'tarjeta',
    invoiceNumber: 'INV-2024-006',
    daysAgo: 9,
    description: 'Tratamiento preventivo contra hongos',
    parcelIndex: 1,
  },
  {
    type: 'ingreso',
    category: 'Subsidios',
    concept: 'Ayuda PAC',
    amount: 3200.0,
    paymentMethod: 'transferencia',
    daysAgo: 25,
    description: 'Pago de subsidio agrícola europeo',
    parcelIndex: 0,
  },
  {
    type: 'gasto',
    category: 'Servicios',
    concept: 'Electricidad',
    amount: 195.3,
    paymentMethod: 'domiciliación',
    invoiceNumber: 'INV-2024-007',
    daysAgo: 1,
    description: 'Factura de electricidad de sistemas de riego',
    parcelIndex: 1,
  },
  {
    type: 'gasto',
    category: 'Maquinaria',
    concept: 'Repuestos cosechadora',
    amount: 485.0,
    paymentMethod: 'transferencia',
    invoiceNumber: 'INV-2024-008',
    daysAgo: 11,
    description: 'Compra de piezas de repuesto para mantenimiento',
    parcelIndex: 2,
  },
  {
    type: 'ingreso',
    category: 'Ventas',
    concept: 'Venta de pimientos',
    amount: 420.75,
    paymentMethod: 'efectivo',
    daysAgo: 4,
    description: 'Venta en mercado local',
    parcelIndex: 2,
  },
  {
    type: 'gasto',
    category: 'Insumos',
    concept: 'Compost orgánico',
    amount: 210.0,
    paymentMethod: 'transferencia',
    invoiceNumber: 'INV-2024-009',
    daysAgo: 16,
    description: 'Compra de abono orgánico certificado',
    parcelIndex: 1,
  },
  {
    type: 'gasto',
    category: 'Servicios',
    concept: 'Seguro agrícola',
    amount: 890.0,
    paymentMethod: 'transferencia',
    invoiceNumber: 'INV-2024-010',
    daysAgo: 30,
    description: 'Póliza anual de seguro para cultivos',
    parcelIndex: 0,
  },
  {
    type: 'ingreso',
    category: 'Ventas',
    concept: 'Venta de lechugas',
    amount: 155.0,
    paymentMethod: 'tarjeta',
    daysAgo: 2,
    description: 'Venta de lechugas ecológicas',
    parcelIndex: 2,
  },
  {
    type: 'gasto',
    category: 'Mantenimiento',
    concept: 'Reparación invernadero',
    amount: 275.5,
    paymentMethod: 'efectivo',
    daysAgo: 13,
    description: 'Reparación de cristales y estructura',
    parcelIndex: 2,
  },
  {
    type: 'gasto',
    category: 'Insumos',
    concept: 'Insecticida ecológico',
    amount: 132.0,
    paymentMethod: 'tarjeta',
    invoiceNumber: 'INV-2024-011',
    daysAgo: 5,
    description: 'Control biológico de plagas',
    parcelIndex: 0,
  },
  {
    type: 'ingreso',
    category: 'Ventas',
    concept: 'Venta de miel',
    amount: 380.0,
    paymentMethod: 'transferencia',
    daysAgo: 19,
    description: 'Venta de producción de apicultura',
    parcelIndex: 2,
  },
  {
    type: 'gasto',
    category: 'Servicios',
    concept: 'Agua de riego',
    amount: 156.8,
    paymentMethod: 'domiciliación',
    invoiceNumber: 'INV-2024-012',
    daysAgo: 1,
    description: 'Tarifa mensual de agua para riego',
    parcelIndex: 1,
  },
  {
    type: 'gasto',
    category: 'Mano de obra',
    concept: 'Técnico fitosanitario',
    amount: 180.0,
    paymentMethod: 'transferencia',
    daysAgo: 8,
    description: 'Servicio de aplicación de tratamientos',
    parcelIndex: 1,
  },
  {
    type: 'ingreso',
    category: 'Ventas',
    concept: 'Venta de aceite de oliva',
    amount: 2150.0,
    paymentMethod: 'transferencia',
    daysAgo: 22,
    description: 'Venta de aceite virgen extra a mayorista',
    parcelIndex: 0,
  },
  {
    type: 'gasto',
    category: 'Insumos',
    concept: 'Abono foliar',
    amount: 98.5,
    paymentMethod: 'tarjeta',
    invoiceNumber: 'INV-2024-013',
    daysAgo: 6,
    description: 'Fertilizante líquido para aplicación foliar',
    parcelIndex: 2,
  },
  {
    type: 'gasto',
    category: 'Maquinaria',
    concept: 'Combustible diésel',
    amount: 340.0,
    paymentMethod: 'tarjeta',
    invoiceNumber: 'INV-2024-014',
    daysAgo: 3,
    description: 'Repostaje de tractores y maquinaria',
    parcelIndex: 0,
  },
  {
    type: 'ingreso',
    category: 'Ventas',
    concept: 'Venta de calabazas',
    amount: 245.0,
    paymentMethod: 'efectivo',
    daysAgo: 11,
    description: 'Venta de calabazas de temporada',
    parcelIndex: 2,
  },
  {
    type: 'gasto',
    category: 'Servicios',
    concept: 'Mantenimiento tractor',
    amount: 425.0,
    paymentMethod: 'transferencia',
    invoiceNumber: 'INV-2024-015',
    daysAgo: 17,
    description: 'Revisión y cambio de aceite completo',
    parcelIndex: 0,
  },
  {
    type: 'gasto',
    category: 'Insumos',
    concept: 'Sustrato para semilleros',
    amount: 85.0,
    paymentMethod: 'efectivo',
    daysAgo: 7,
    description: 'Compra de sustrato especial para germinación',
    parcelIndex: 2,
  },
  {
    type: 'ingreso',
    category: 'Ventas',
    concept: 'Venta de berenjenas',
    amount: 198.5,
    paymentMethod: 'transferencia',
    daysAgo: 4,
    description: 'Venta de berenjenas a cooperativa',
    parcelIndex: 2,
  },
  {
    type: 'gasto',
    category: 'Insumos',
    concept: 'Sistema de riego por goteo',
    amount: 1250.0,
    paymentMethod: 'transferencia',
    invoiceNumber: 'INV-2024-016',
    daysAgo: 28,
    description: 'Instalación de sistema de riego automático',
    parcelIndex: 1,
  },
  {
    type: 'ingreso',
    category: 'Ventas',
    concept: 'Venta de zanahorias',
    amount: 312.0,
    paymentMethod: 'efectivo',
    daysAgo: 9,
    description: 'Venta de zanahorias en mercado agrícola',
    parcelIndex: 2,
  },
  {
    type: 'gasto',
    category: 'Insumos',
    concept: 'Plástico para invernadero',
    amount: 380.0,
    paymentMethod: 'tarjeta',
    invoiceNumber: 'INV-2024-017',
    daysAgo: 21,
    description: 'Reposición de cobertura de invernadero',
    parcelIndex: 2,
  },
  {
    type: 'gasto',
    category: 'Servicios',
    concept: 'Certificación ecológica',
    amount: 450.0,
    paymentMethod: 'transferencia',
    invoiceNumber: 'INV-2024-018',
    daysAgo: 35,
    description: 'Renovación anual de certificación bio',
    parcelIndex: 0,
  },
  {
    type: 'ingreso',
    category: 'Ventas',
    concept: 'Venta de fresas',
    amount: 565.0,
    paymentMethod: 'transferencia',
    daysAgo: 12,
    description: 'Venta de fresas de invernadero',
    parcelIndex: 2,
  },
  {
    type: 'gasto',
    category: 'Mano de obra',
    concept: 'Podadores profesionales',
    amount: 620.0,
    paymentMethod: 'efectivo',
    daysAgo: 24,
    description: 'Equipo especializado en poda de viñedos',
    parcelIndex: 2,
  },
  {
    type: 'gasto',
    category: 'Insumos',
    concept: 'Fitosanitarios autorizados',
    amount: 215.75,
    paymentMethod: 'tarjeta',
    invoiceNumber: 'INV-2024-019',
    daysAgo: 10,
    description: 'Productos fitosanitarios certificados',
    parcelIndex: 1,
  },
  {
    type: 'ingreso',
    category: 'Alquiler',
    concept: 'Alquiler de parcela',
    amount: 800.0,
    paymentMethod: 'transferencia',
    daysAgo: 15,
    description: 'Pago trimestral de alquiler de terreno',
    parcelIndex: 1,
  },
  {
    type: 'gasto',
    category: 'Maquinaria',
    concept: 'Fumigadora nueva',
    amount: 2850.0,
    paymentMethod: 'transferencia',
    invoiceNumber: 'INV-2024-020',
    daysAgo: 40,
    description: 'Compra de fumigadora de alta eficiencia',
    parcelIndex: 0,
  },
  {
    type: 'ingreso',
    category: 'Ventas',
    concept: 'Venta de uvas',
    amount: 1780.0,
    paymentMethod: 'transferencia',
    daysAgo: 26,
    description: 'Venta de uvas de mesa a distribuidora',
    parcelIndex: 2,
  },
  {
    type: 'gasto',
    category: 'Servicios',
    concept: 'Veterinario',
    amount: 95.0,
    paymentMethod: 'efectivo',
    daysAgo: 19,
    description: 'Revisión sanitaria de colmenas',
    parcelIndex: 2,
  },
  {
    type: 'gasto',
    category: 'Insumos',
    concept: 'Bandejas de semillero',
    amount: 68.5,
    paymentMethod: 'tarjeta',
    invoiceNumber: 'INV-2024-021',
    daysAgo: 5,
    description: 'Material para producción de planteles',
    parcelIndex: 2,
  },
  {
    type: 'ingreso',
    category: 'Ventas',
    concept: 'Venta de hortalizas mixtas',
    amount: 432.0,
    paymentMethod: 'efectivo',
    daysAgo: 3,
    description: 'Caja mixta de hortalizas de temporada',
    parcelIndex: 2,
  },
  {
    type: 'gasto',
    category: 'Mantenimiento',
    concept: 'Limpieza de pozos',
    amount: 290.0,
    paymentMethod: 'transferencia',
    invoiceNumber: 'INV-2024-022',
    daysAgo: 23,
    description: 'Mantenimiento y limpieza de sistema de pozos',
    parcelIndex: 1,
  },
  {
    type: 'gasto',
    category: 'Servicios',
    concept: 'Gestoría agrícola',
    amount: 175.0,
    paymentMethod: 'domiciliación',
    invoiceNumber: 'INV-2024-023',
    daysAgo: 1,
    description: 'Cuota mensual de gestoría',
    parcelIndex: 0,
  },
  {
    type: 'ingreso',
    category: 'Ventas',
    concept: 'Venta de maíz',
    amount: 945.0,
    paymentMethod: 'transferencia',
    daysAgo: 27,
    description: 'Venta de cosecha de maíz',
    parcelIndex: 1,
  },
  {
    type: 'gasto',
    category: 'Insumos',
    concept: 'Malla antihierba',
    amount: 156.0,
    paymentMethod: 'tarjeta',
    invoiceNumber: 'INV-2024-024',
    daysAgo: 14,
    description: 'Malla para control de malas hierbas',
    parcelIndex: 0,
  },
  {
    type: 'gasto',
    category: 'Maquinaria',
    concept: 'Neumáticos para tractor',
    amount: 540.0,
    paymentMethod: 'transferencia',
    invoiceNumber: 'INV-2024-025',
    daysAgo: 29,
    description: 'Cambio de neumáticos traseros',
    parcelIndex: 0,
  },
  {
    type: 'ingreso',
    category: 'Ventas',
    concept: 'Venta de patatas',
    amount: 378.5,
    paymentMethod: 'efectivo',
    daysAgo: 8,
    description: 'Venta de patatas nuevas',
    parcelIndex: 1,
  },
  {
    type: 'gasto',
    category: 'Servicios',
    concept: 'Análisis fitosanitario',
    amount: 165.0,
    paymentMethod: 'transferencia',
    invoiceNumber: 'INV-2024-026',
    daysAgo: 16,
    description: 'Análisis de detección de plagas',
    parcelIndex: 1,
  },
  {
    type: 'gasto',
    category: 'Insumos',
    concept: 'Tutores para tomates',
    amount: 92.0,
    paymentMethod: 'efectivo',
    daysAgo: 11,
    description: 'Cañas y tutores para cultivo',
    parcelIndex: 2,
  },
  {
    type: 'ingreso',
    category: 'Ventas',
    concept: 'Venta de cebollas',
    amount: 215.0,
    paymentMethod: 'transferencia',
    daysAgo: 13,
    description: 'Venta de cebollas dulces',
    parcelIndex: 1,
  },
  {
    type: 'gasto',
    category: 'Mantenimiento',
    concept: 'Pintura de almacén',
    amount: 185.0,
    paymentMethod: 'tarjeta',
    daysAgo: 31,
    description: 'Mantenimiento y pintura de instalaciones',
    parcelIndex: 0,
  },
  {
    type: 'gasto',
    category: 'Insumos',
    concept: 'Aminoácidos foliares',
    amount: 128.0,
    paymentMethod: 'tarjeta',
    invoiceNumber: 'INV-2024-027',
    daysAgo: 6,
    description: 'Bioestimulantes para crecimiento',
    parcelIndex: 2,
  },
  {
    type: 'ingreso',
    category: 'Ventas',
    concept: 'Venta de calabacines',
    amount: 267.5,
    paymentMethod: 'efectivo',
    daysAgo: 5,
    description: 'Venta de calabacines en mercado local',
    parcelIndex: 2,
  },
  {
    type: 'gasto',
    category: 'Servicios',
    concept: 'Transporte de productos',
    amount: 145.0,
    paymentMethod: 'transferencia',
    daysAgo: 4,
    description: 'Flete para entrega de cosecha',
    parcelIndex: 0,
  },
  {
    type: 'gasto',
    category: 'Mano de obra',
    concept: 'Recolección de fresas',
    amount: 385.0,
    paymentMethod: 'efectivo',
    daysAgo: 12,
    description: 'Jornaleros para cosecha de fresas',
    parcelIndex: 2,
  },
  {
    type: 'ingreso',
    category: 'Ventas',
    concept: 'Venta de ajos',
    amount: 295.0,
    paymentMethod: 'transferencia',
    daysAgo: 17,
    description: 'Venta de ajos secos',
    parcelIndex: 1,
  },
  {
    type: 'gasto',
    category: 'Insumos',
    concept: 'Bolsas de envasado',
    amount: 76.5,
    paymentMethod: 'tarjeta',
    invoiceNumber: 'INV-2024-028',
    daysAgo: 7,
    description: 'Material de envasado para venta',
    parcelIndex: 2,
  },
  {
    type: 'gasto',
    category: 'Servicios',
    concept: 'Internet rural',
    amount: 55.0,
    paymentMethod: 'domiciliación',
    invoiceNumber: 'INV-2024-029',
    daysAgo: 1,
    description: 'Conexión para sistemas de monitoreo',
    parcelIndex: 0,
  },
  {
    type: 'ingreso',
    category: 'Ventas',
    concept: 'Venta de espárragos',
    amount: 685.0,
    paymentMethod: 'transferencia',
    daysAgo: 20,
    description: 'Venta de espárragos verdes premium',
    parcelIndex: 1,
  },
  {
    type: 'gasto',
    category: 'Maquinaria',
    concept: 'Batería para tractor',
    amount: 175.0,
    paymentMethod: 'tarjeta',
    invoiceNumber: 'INV-2024-030',
    daysAgo: 15,
    description: 'Reemplazo de batería principal',
    parcelIndex: 0,
  },
  {
    type: 'gasto',
    category: 'Insumos',
    concept: 'Corrector de pH',
    amount: 88.0,
    paymentMethod: 'efectivo',
    daysAgo: 9,
    description: 'Productos para ajuste de pH del suelo',
    parcelIndex: 1,
  },
  {
    type: 'ingreso',
    category: 'Ventas',
    concept: 'Venta de sandías',
    amount: 825.0,
    paymentMethod: 'transferencia',
    daysAgo: 25,
    description: 'Venta de sandías de temporada',
    parcelIndex: 2,
  },
  {
    type: 'gasto',
    category: 'Mantenimiento',
    concept: 'Revisión bomba de agua',
    amount: 225.0,
    paymentMethod: 'transferencia',
    invoiceNumber: 'INV-2024-031',
    daysAgo: 22,
    description: 'Mantenimiento preventivo de bomba',
    parcelIndex: 1,
  },
  {
    type: 'gasto',
    category: 'Servicios',
    concept: 'Teléfono móvil',
    amount: 45.0,
    paymentMethod: 'domiciliación',
    invoiceNumber: 'INV-2024-032',
    daysAgo: 1,
    description: 'Línea móvil para gestión de finca',
    parcelIndex: 0,
  },
  {
    type: 'ingreso',
    category: 'Ventas',
    concept: 'Venta de melones',
    amount: 542.0,
    paymentMethod: 'efectivo',
    daysAgo: 18,
    description: 'Venta de melones amarillos',
    parcelIndex: 2,
  },
  {
    type: 'gasto',
    category: 'Insumos',
    concept: 'Estacas de sujeción',
    amount: 115.0,
    paymentMethod: 'tarjeta',
    daysAgo: 13,
    description: 'Material para soporte de plantas',
    parcelIndex: 2,
  },
  {
    type: 'gasto',
    category: 'Mano de obra',
    concept: 'Transplante de planteles',
    amount: 295.0,
    paymentMethod: 'efectivo',
    daysAgo: 10,
    description: 'Mano de obra para transplante',
    parcelIndex: 2,
  },
  {
    type: 'ingreso',
    category: 'Ventas',
    concept: 'Venta de remolacha',
    amount: 186.0,
    paymentMethod: 'transferencia',
    daysAgo: 21,
    description: 'Venta de remolacha de mesa',
    parcelIndex: 1,
  },
]
